services:
  backend:
    image: golang:1.24.1
    container_name: backend_app
    working_dir: /backend
    volumes:
      - ./backend:/backend
    command: ["sh", "-c", "go run cmd/main.go"]
    ports:
      - "8080:8080"
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - GO_ENV=development
    tty: true

  mariadb:
    image: mariadb:11.7.2
    container_name: mariadb_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 5s
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  database:
